version: '3.8'
services:

  postgres:
    image: postgres:13
    container_name: empregos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  
volumes:
  postgres: